### PR TITLE
Updated GetIdentity, Added a way to send big file via stream

### PR DESCRIPTION
**Pull request by Xemuth**
Two year ago I posted about this merge request: 
https://www.ultimatepp.org/forums/index.php?t=msg&th=11649&start=0&
and also this one:
https://www.ultimatepp.org/forums/index.php?t=msg&th=11017&start=0&

nowaday all thoses are still usefull but has not been accepted yet. 

The need to handle Identity when it's not in the first position allow to use external JS libs without having to patch them.
Moreover, Ability to send file using stream allow skylark to deal with large file.

To this day all my skylark app rely on one or both features.

Thanks in advance

### CODE REVIEW

**Comment by Xemuth** [comment]
@mirek-fidler  it is possible that I write one Skylark example that download file.

**Comment by mirek-fidler** [comment]
Hi,

admittedly Skylark was low on my priority list, sorry. I am ready to yield
complete control over it to somebody - are you willing? :)

Mirek

**Comment by Xemuth** [comment]
Hello Mirek, 

Thanks for your consideration. Well, I really like Skylark however I'm not present much this year. If you don't mind then I will do my best to support and update skylark

**Comment by mirek-fidler** [comment]
Excellent. I think there are 2 ways how to go about it:

- you branch Skylark and I will redirect UppHub to your new repo

or

- I will add you as collaborator (already set the invitation)

Mirek

**Comment by Xemuth** [comment]
SInce the project is your I prefere to be collaborator

**Comment by Xemuth** [comment]
Thanks Mirek

**Pull request merged**
